BASE_URL = "https://cvedb.shodan.io"
DEFAULT_LIMIT = 100
DEFAULT_TIMEOUT = 30
API_VERSION = "v1"

# HTTP Status Codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_TOO_MANY_REQUESTS = 429 